name: Build nightly

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
        with:
          submodules: recursive
      - name: Setup node
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f
        with:
          node-version: 24
      - name: Setup pnpm
        uses: pnpm/action-setup@b9e1dbc72ff7358f971cc0b7c62c7a0d83f1068b
        with:
          version: 10
      - name: Install deps, esbuild, tsgo
        run: |
          pnpm install
          pnpm --allow-build=esbuild add esbuild
          pnpm --allow-build=@typescript/native-preview add @typescript/native-preview
      - name: Prepare Taut plugins
        run: |
          git clone https://github.com/jeremy46231/taut
          (cd taut && git checkout 162293a4ed8c18e382e6f0157f4161586170e789)
          mkdir -p src/plugins/taut/
          for p in taut/plugins/*; do
            plugin="$(basename "$p")"
            sed -e 's#\.\./core/Plugin#../../taut#g' \
              -e "#import.*from 'console'#d" \
              -e 's#React#globalThis.React#g' \
              taut/plugins/"$plugin" > src/plugins/taut/"$plugin"
          done
      - name: Build
        run: |
          NIGHTLY=1 ./scripts/prepare-userscript.sh
      - name: Publish userscript
        uses: softprops/action-gh-release@60cfd9a691d814dcf0d094598101c5cb61cd1646
        with:
          name: nightly
          prerelease: true
          files: |
            ./out/dist-userscript.user.js
